// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqK1lLtAol9hV_h8SVCshjli4IMcGQ8Lg',
    appId: '1:204572132227:web:419ebc74c781b9de232cb6',
    messagingSenderId: '204572132227',
    projectId: 'auth-mappers',
    authDomain: 'auth-mappers.firebaseapp.com',
    storageBucket: 'auth-mappers.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBz652eeHl8GHTjEocAMvvNHq_HU8vfN1M',
    appId: '1:204572132227:android:c67c7884c684eeb1232cb6',
    messagingSenderId: '204572132227',
    projectId: 'auth-mappers',
    storageBucket: 'auth-mappers.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuYfzbBODWf0bGWd_ZQAGN8lWXw_uRMC4',
    appId: '1:204572132227:ios:eb7b334148de6daa232cb6',
    messagingSenderId: '204572132227',
    projectId: 'auth-mappers',
    storageBucket: 'auth-mappers.firebasestorage.app',
    iosBundleId: 'com.example.authMappers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuYfzbBODWf0bGWd_ZQAGN8lWXw_uRMC4',
    appId: '1:204572132227:ios:eb7b334148de6daa232cb6',
    messagingSenderId: '204572132227',
    projectId: 'auth-mappers',
    storageBucket: 'auth-mappers.firebasestorage.app',
    iosBundleId: 'com.example.authMappers',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqK1lLtAol9hV_h8SVCshjli4IMcGQ8Lg',
    appId: '1:204572132227:web:2624225433204757232cb6',
    messagingSenderId: '204572132227',
    projectId: 'auth-mappers',
    authDomain: 'auth-mappers.firebaseapp.com',
    storageBucket: 'auth-mappers.firebasestorage.app',
  );
}
